### PR TITLE
fix(FAD): fix lyrics alignment, bug fixes

### LINKED ISSUE #58: [Full App Display][BUG]
Whyyyyy like this
Screenshot (206)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Spotify Version: 1.2.13.661
 - Spicetify Version: v2.20.1

### PR DESCRIPTION
**Pull request by Seudonym**
The previous pull request had a bug where the controls weren't working. Fixed alignment and bugs (not tested on vertical monitors)
Closes #58

### CODE REVIEW

**Comment by mccalltristan** [comment]
doesnt fix it

**Comment by NarQq** [comment]
> doesnt fix it, im on a horizontal monitor 1920x1080 

same for me

**Comment by Seudonym** [comment]
> doesnt fix it, im on a horizontal monitor 1920x1080

I've tried it on a different device with 1920x1080 resolution. It seems to work fine there and on a few other devices. Are you sure you are not using the marketplace version? If you have the fixed one in your Extensions folder, did you make sure to run 'spicetify apply' after?

**Comment by ohitstom** [comment]
may I suggest you follow what we did officially for normal fullappdisplay.

**Comment by Seudonym** [comment]
I didn't realize that there was a fix for this. Closing my request.

**Pull request closed without merging**
